config/routes.rb
Community::Application.routes.draw do
  devise_for :users
  root to: 'welcome#dashboard'
  resources :residents do
    resources :invoices, only: [:create]
  end

  resources :buildings do
    resources :units
  end

  resources :users do
    post '/approve', to: 'users#approve'
    delete '/unapprove', to: 'users#unapprove'
  end

  resources :payments
  resources :accounts

  resources :transactions do
    collection do
      post 'withdraw'
      post 'deposit'
      post 'transfer'
      get 'residents'
      post 'pay_management_fees'
    end
  end

  resources :transaction_types

  resources :invoices
end

app/models/building.rb
#encoding: utf-8
class Building < ActiveRecord::Base
  attr_accessible :name, :updated_by, :created_by
  has_many :units, dependent: :destroy
  validates_presence_of :name

  after_create :build_create_comment
  before_update :build_update_comment

  acts_as_commentable

  def building_name
    self.name + '棟'
  end

  def created_user
    User.find(self.created_by)
  end

  def updated_user
    User.find(self.updated_by)
  end

  protected

  def build_create_comment
    comment = Comment.build_from(self, self.created_by, "#{self.created_user.name}建立了#{self.name}")
    comment.save
  end

  def build_update_comment
    comment = Comment.build_from(self, self.updated_by, "#{self.updated_user.name}更新了#{self.name}</br>更新內容：#{self.changes}")
    comment.save
  end

end

app/controllers/buildings_controller.rb
#encoding: utf-8
class BuildingsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @buildings = Building.paginate(page: params[:page])
  end

  def new
    @building = Building.new
  end

  def create
    @building = Building.new(params[:building])
    @building.created_by = current_user
    if @building.save
      redirect_to buildings_path, notice: "成功建立#{@building.name}"
    else
      render :new
    end
  end

  def edit
    @building = Building.find(params[:id])
  end

  def update
    @building = Building.find(params[:id])
    @building.updated_by = current_user
    if @building.update_attributes(params[:building])
      redirect_to buildings_path, notice: "#{@building.name}更新成功"
    else
      render :edit
    end
  end
end

app/views/buildings/_building.html.slim
.building.span3
  .well
    h2.pull-left #{building.name}棟
    = link_to '編輯', edit_building_path(building), class: 'pull-right btn'
    '
    = link_to '新增單位', new_building_unit_path(building), class: 'pull-right btn'
    .clearfix
    hr
    ul.unstyled
      - building.units.each do |unit|
        li
          - if unit.resident.present?
            .unit.living-unit.alert.alert-success
              h5= unit.address
              = link_to unit.resident_name, resident_path(unit.resident)
              br
              .actions
                = link_to '編輯', edit_building_unit_path(building, unit), class: 'btn btn-mini'
                = link_to '刪除', building_unit_path(building, unit), method: :delete, confirm: '確認要刪除此單位嗎？', class: 'btn btn-danger'
          - else
            .unit.empty.alert.alert-info
              h5= unit.address
              .actions
                = link_to '編輯', edit_building_unit_path(building, unit), class: 'btn btn-mini pull-right'
                = link_to '刪除', building_unit_path(building, unit), method: :delete, confirm: '確認要刪除此單位嗎？', class: 'btn btn-danger btn-mini'

app/views/buildings/_form.html.slim
= simple_form_for @building, html: { class: 'form-horizontal' } do |f|
  = f.input :name, label: '棟名', hint: "例如:'A' 代表A棟"
  .form-actions
    = f.submit '送出', class: 'btn btn-primary'

app/views/buildings/edit.html.slim
.row
  .span12
    header.page-header
      h1 編輯#{@building.building_name}
    = render 'form'
    hr
    header.page-header
      h1 事件記錄
    = render partial: 'shared/comments', locals: { comments: @building.comment_threads }

app/views/buildings/index.html.slim
.row
  .span12
    h1 大樓管理
    = link_to '新增大樓', new_building_path, class: 'btn btn-primary pull-right'
    .clearfix
    - @buildings.each_slice(4) do |a, b, c, d|
      .row
        - if a
          = render :partial => 'building', locals: { building: a }
        - if b
          = render :partial => 'building', locals: { building: b }
        - if c
          = render :partial => 'building', locals: { building: c }
        - if d
          = render :partial => 'building', locals: { building: d }

app/views/buildings/new.html.slim
.row
  .span12
    header.page-header
      h1 新增大樓
    = render 'form'