config/routes.rb
Community::Application.routes.draw do
  devise_for :users
  root to: 'welcome#dashboard'
  resources :residents do
    resources :invoices, only: [:create]
  end

  resources :buildings do
    resources :units
  end

  resources :users do
    post '/approve', to: 'users#approve'
    delete '/unapprove', to: 'users#unapprove'
  end

  resources :payments
  resources :accounts

  resources :transactions do
    collection do
      post 'withdraw'
      post 'deposit'
      post 'transfer'
      get 'residents'
      post 'pay_management_fees'
    end
  end

  resources :transaction_types

  resources :invoices
end

app/models/resident.rb
#encoding: utf-8
class Resident < ActiveRecord::Base
  attr_accessible :bike_num, :car_num, :created_by, :name, :phone, :pid, :rent, :unit_id, :updated_by

  acts_as_commentable

  after_create :build_create_comment
  before_update :build_update_comment

  CAR_FEE = 200
  BIKE_FEE = 100

  has_many :payments
  belongs_to :unit

  scope :current_residents, where("unit_id IS NOT NULL")
  scope :idle, where("unit_id IS NULL")

  delegate :num, :address, :building, :pin, to: :unit, allow_nil: true, prefix: true

  def build_payment(user)
    payment = self.payments.build
    payment.management_fee = self.unit.management_fee
    payment.car_fee = CAR_FEE if self.car_num.present?
    payment.bike_fee = BIKE_FEE if self.bike_num.present?
    payment.created_by = user.id
    payment.save
  end

  def building_unit
    return if self.unit.nil?
    "#{self.unit.building.building_name}-#{self.unit.unit_num}"
  end

  def unit_address
    self.unit.try(:address)
  end

  def management_fee
    self.unit.try(:management_fee)
  end

  def created_user
    User.find(self.created_by)
  end

  def updated_user
    User.find(self.updated_by)
  end

  protected

  def build_create_comment
    comment = Comment.build_from(self, self.created_by, "#{self.created_user.name}建立了#{self.name}")
    comment.save
  end

  def build_update_comment
    comment = Comment.build_from(self, self.updated_by, "#{self.updated_user.name}更新了#{self.name}</br>更新內容：#{self.changes}")
    comment.save
  end

end

app/controllers/residents_controller.rb
#encoding: utf-8
class ResidentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @residents = Resident.paginate(page: params[:page])
  end

  def show
    @resident = Resident.find(params[:id])
    @accounts = Account.all
  end

  def new
    @resident = Resident.new
  end

  def create
    @resident = Resident.new(params[:resident])
    @resident.created_by = current_user.id

    if @resident.save
      redirect_to resident_path(@resident), notice: "#{@resident.name}建立成功！"
    else
      render :new, notice: @resident.errors
    end
  end

  def edit
    @resident = Resident.find(params[:id])
  end

  def update
    @resident = Resident.find(params[:id])
    @resident.updated_by = current_user.id

    if @resident.update_attributes(params[:resident])
      redirect_to resident_path(@resident), notice: "成功更新了#{@resident.name}的資料"
    end
  end
end

app/views/residents/_form.html.slim
= f.input :name, label: '姓名'
= f.input :pid, label: '身分證字號'
= f.input :phone, label: '電話號碼'
= f.input :car_num, label: '汽車車號'
= f.input :bike_num, label: '機車車號'
= f.association :unit, :as => :grouped_select, collection: Building.all, label_method: :unit_num, group_method: :units, group_label_method: :building_name, label: '居住單位'
= f.input :rent, label: '是否為租貸'
.form-actions
  = f.submit '送出', class: 'btn btn-primary'

app/views/residents/_residents.html.slim
table.table.table-striped.table-bordered.table-hover.table-condensed
  thead
    tr
      th 住戶
      th 單位
      th 身分證字號
      th 電話
      th 汽車車號
      th 機車車號
      th 是否租貸
      th 操作
  tbody
    - residents.each do |resident|
      tr
        td= link_to resident.name, resident_path(resident)
        td= resident.unit_address
        td= resident.pid
        td= resident.phone
        td= resident.car_num
        td= resident.bike_num
        td= resident.rent?
        td.btn-group
          = link_to edit_resident_path(resident), class: 'btn', rel: 'tooltip', title: '編輯' do
            i.icon-edit
          = link_to resident_path(resident), method: :delete, class: 'btn btn-danger' do
            i.icon-remove

app/views/residents/edit.html.slim
.row
  .span12
    header.page-header
      h1 編輯 #{@resident.name}
    = simple_form_for @resident, html: { class: 'form-horizontal' } do |f|
      = render :partial => 'form', locals: { :f => f }

app/views/residents/index.html.slim
.row
  .span12
    h1 住戶列表
    = link_to '新增住戶資料', new_resident_path, class: 'btn btn-primary pull-right'
    .clearfix
    ul.nav.nav-tabs
      li.active
        a href="#residents" data-toggle="tab" 住戶
      li
        a href="#idle" data-toggle="tab" 非住戶
    .tab-content
      #residents.tab-pane.active
        = render partial: 'residents', locals: { residents: @residents.current_residents }
      #idle.tab-pane
        = render partial: 'residents', locals: { residents: @residents.idle }
  .span12
    = will_paginate @residents

app/views/residents/new.html.slim
.row
  .span12
    header.page-header
      h1 新增住戶資料
    = simple_form_for @resident, html: { class: 'form-horizontal' } do |f|
      = render :partial => 'form', locals: { :f => f }

app/views/residents/show.html.slim
.row
  .span12
    header.page-header
      h1.pull-left #{@resident.name} 的資料
      = link_to '編輯', edit_resident_path(@resident), class: 'btn btn-primary btn-large pull-right'
      .clearfix

    table.table.table-striped.table-bordered.table-hover.table-condensed
      thead
        tr
          th 住戶
          th 單位
          th 身分證字號
          th 電話
          th 汽車車號
          th 機車車號
          th 是否租貸
      tbody
        tr
          td= @resident.name
          td= @resident.unit_address
          td= @resident.pid
          td= @resident.phone
          td= @resident.car_num
          td= @resident.bike_num
          td= @resident.rent?

    hr
    ul.nav.nav-tabs
      li.active
        a href="#unpaid_payments" data-toggle="tab" 待繳費用
      li
        a href="#paid_payments" data-toggle="tab" 繳費記錄
      li
        a href="#history" data-toggle="tab" 事件記錄
    .tab-content
      .tab-pane.active#unpaid_payments
        = form_tag resident_invoices_path(@resident) do
          table.table.table-striped.table-bordered.table-hover.table-condensed
            thead
              tr
                th
                th 日期
                th 管理費
                th 汽車清潔費
                th 機車清潔費
                th 總金額
            tbody
              - @resident.payments.unpaid_records.each do |payment|
                tr
                  td= check_box_tag 'payment_ids[]', payment.id unless payment.paid?
                  td= l payment.created_at, format: '%Y年%b'
                  td= currency payment.management_fee
                  td= currency payment.car_fee
                  td= currency payment.bike_fee
                  td= currency payment.total_fee
          label 繳費
          '
          = select_tag "account_id", options_from_collection_for_select(@accounts, :id, :name, Account.cash_id)
          '
          = submit_tag "繳費並列印收據", :class => 'btn btn-primary'
      .tab-pane#paid_payments
        table.table.table-striped.table-bordered.table-hover.table-condensed
          thead
            tr
              th 日期
              th 管理費
              th 汽車清潔費
              th 機車清潔費
              th 總金額
              th 結清
              th 收據
          tbody
            - @resident.payments.paid_records.each do |payment|
              tr
                td= l payment.created_at, format: '%Y年%b'
                td= currency payment.management_fee
                td= currency payment.car_fee
                td= currency payment.bike_fee
                td= currency payment.total_fee
                td= l payment.paid_date, format: :short
                td= link_to payment.invoice_num, invoice_path(payment.invoice), target: '_blank'
      .tab-pane#history
        = render partial: 'shared/comments', locals: { comments: @resident.comment_threads }