config/routes.rb
Community::Application.routes.draw do
  devise_for :users
  root to: 'welcome#dashboard'
  resources :residents do
    resources :invoices, only: [:create]
  end

  resources :buildings do
    resources :units
  end

  resources :users do
    post '/approve', to: 'users#approve'
    delete '/unapprove', to: 'users#unapprove'
  end

  resources :payments
  resources :accounts

  resources :transactions do
    collection do
      post 'withdraw'
      post 'deposit'
      post 'transfer'
      get 'residents'
      post 'pay_management_fees'
    end
  end

  resources :transaction_types

  resources :invoices
end

app/models/payment.rb
#encoding: utf-8
class Payment < ActiveRecord::Base
  attr_accessible :bike_fee, :car_fee, :created_by, :management_fee, :paid_date, :updated_by, :resident_id, :transactions_attributes, :invoice

  belongs_to :resident
  belongs_to :invoice
  has_many :transactions
  accepts_nested_attributes_for :transactions,
                                :reject_if => lambda { |a| a[:amount].blank? }

  after_create :build_create_comment
  before_update :build_update_comment

  delegate :num, to: :invoice, allow_nil: true, prefix: true

  scope :paid_records, where('paid_date IS NOT NULL')
  scope :unpaid_records, where('paid_date IS NULL')

  acts_as_commentable

  def self.create_this_month_fee(user)
    Resident.current_residents.each do |resident|
      resident.build_payment(user)
    end
    Account.all.each do |account|
      account.checkout(user)
    end
  end

  def month
    I18n.l self.created_at.beginning_of_month, format: '%B'
  end

  def pay(invoice, user)
    update_attributes(paid_date: Time.now,
                      invoice: invoice,
                      updated_by: user.id)
    save!
  end

  def paid?
    self.paid_date?
  end

  def created_user
    User.find(self.created_by)
  end

  def updated_user
    User.find(self.updated_by)
  end

  def total_fee
    management_fee + car_fee + bike_fee
  end

  protected

  def build_create_comment
    comment = Comment.build_from(self, self.created_by, "#{self.created_user.name}產生本月費用共$#{total_fee}")
    comment.save
  end

  def build_update_comment
    comment = Comment.build_from(self, self.updated_by, "#{self.updated_user.name}完成了這次繳費")
    comment.save
  end

end

app/controllers/payments_controller.rb
#encoding: utf-8
class PaymentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @payments = Payment.paginate(page: params[:page])
  end

  def new
    Payment.create_this_month_fee(current_user)
    redirect_to payments_path, notice: '本月費用已產生成功'
  end
end

app/views/payments/index.html.slim
.row
  .span12
    h1 住戶費用管理
    = link_to '建立本月費用', new_payment_path, class: 'btn btn-primary pull-right'
    .clearfix
    hr
    table.table.table-striped.table-bordered.table-hover.table-condensed
      thead
        tr
          th 日期
          th 住戶
          th 管理費
          th 汽車清潔費
          th 機車清潔費
          th 總金額
          th 結清
          th 收據
      tbody
        - @payments.each do |payment|
          tr
            td= l payment.created_at, format: '%Y年%b'
            td= link_to payment.resident.name, resident_path(payment.resident)
            td= currency payment.management_fee
            td= currency payment.car_fee
            td= currency payment.bike_fee
            td= currency payment.total_fee
            td= l payment.paid_date, format: :short if payment.paid_date
            td= link_to payment.invoice.num, invoice_path(payment.invoice), target: '_blank' if payment.paid?