config/routes.rb
Community::Application.routes.draw do
  devise_for :users
  root to: 'welcome#dashboard'
  resources :residents do
    resources :invoices, only: [:create]
  end

  resources :buildings do
    resources :units
  end

  resources :users do
    post '/approve', to: 'users#approve'
    delete '/unapprove', to: 'users#unapprove'
  end

  resources :payments
  resources :accounts

  resources :transactions do
    collection do
      post 'withdraw'
      post 'deposit'
      post 'transfer'
      get 'residents'
      post 'pay_management_fees'
    end
  end

  resources :transaction_types

  resources :invoices
end

app/models/transaction_type.rb
#encoding: utf-8
class TransactionType < ActiveRecord::Base
  attr_accessible :description, :name, :self_type

  TYPES = %w{ 收入 支出 }

  scope :deposit_only, where(self_type: '收入')
  scope :withdraw_only, where(self_type: '支出')

  def self.management_fee
    where(name: '管理費收入').first
  end

  def self.car_fee
    where(name: '汽車清潔費收入').first
  end

  def self.bike_fee
    where(name: '機車清潔費收入').first
  end
end

app/controllers/transactions_controller.rb
#encoding: utf-8
class TransactionsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @transaction = Transaction.new
  end

  def withdraw
    @transaction = Transaction.new(params[:transaction])
    if @transaction.do_withdraw(current_user)
      redirect_to transactions_path, notice: '交易成功'
    else
      render :new
    end
  end

  def deposit
    @transaction = Transaction.new(params[:transaction])
    if @transaction.do_deposit(current_user)
      redirect_to transactions_path, notice: '交易成功'
    else
      render :new
    end
  end

  def transfer
    @transaction = Transaction.new(params[:transaction])
    if @transaction.do_transfer(current_user)
      redirect_to transactions_path, notice: '交易成功'
    else
      render :new
    end
  end

  def index
    @transactions = Transaction.today_records
  end
end

app/views/transactions/_transactions.html.slim
table.table.table-striped.table-bordered.table-hover.table-condensed
  thead
    tr
      th 交易時間
      th 處理人
      th 收入/支出/轉帳
      th 交易分類
      th 備註
      th 交易金額
  tbody
    - transactions.each do |transaction|
      tr
        td= l transaction.created_at, format: :short
        td= transaction.created_user.name
        td= show_transaction_type_badge(transaction)
        td= transaction.transaction_type.try(:name)
        td= transaction.description
        td= currency transaction.amount

app/views/transactions/index.html.slim
.row
  .span12
    h1 本日交易
    .clearfix
    = render partial: 'transactions', locals: { transactions: @transactions }

app/views/transactions/new.html.slim
.row
  .span12
    header.page-header
      h1 新增交易
    ul.nav.nav-tabs
      li.active
        a href="#withdraw" data-toggle="tab" 支出
      li
        a href="#deposit" data-toggle="tab" 收入
      li
        a href="#transfer" data-toggle="tab" 轉帳
    .tab-content
      .tab-pane.active#withdraw
        = simple_form_for @transaction, url: withdraw_transactions_path, html: { class: 'form-horizontal' } do |f|
          = f.association :transaction_type, label: '支出類型', collection: TransactionType.withdraw_only, prompt: '選擇支出種類'
          = f.association :from_account, label: '從帳戶', label_method: lambda { |account| name_with_balance account }, value_method: :id, prompt: '選擇帳戶'

          = f.input :amount, label: '金額'
          = f.input :description, label: '備註', input_html: { rows: 10 }
          .form-actions
            = f.submit '送出', class: 'btn btn-primar'
      .tab-pane#deposit
        = simple_form_for @transaction, url: deposit_transactions_path, html: { class: 'form-horizontal' } do |f|
          = f.association :transaction_type, label: '收入類型', collection: TransactionType.deposit_only, prompt:'選擇收入種類'
          = f.association :to_account, label: '至帳戶', label_method: lambda { |account| name_with_balance account }, value_method: :id, prompt: '選擇帳戶'
          = f.input :amount, label: '金額'
          = f.input :description, label: '備註', input_html: { rows: 10 }
          .form-actions
            = f.submit '送出', class: 'btn btn-primar'
      .tab-pane#transfer
        = simple_form_for @transaction, url: transfer_transactions_path, html: { class: 'form-horizontal' } do |f|
          = f.association :from_account, label: '從帳戶', label_method: lambda { |account| name_with_balance account }, value_method: :id, prompt: '選擇帳戶'

          = f.association :to_account, label: '至帳戶', label_method: lambda { |account| name_with_balance account }, value_method: :id, prompt: '選擇帳戶'

          = f.input :amount, label: '金額'
          = f.input :description, label: '備註', input_html: { rows: 10 }
          .form-actions
            = f.submit '送出', class: 'btn btn-primar'